version: '2'
services:
  jenkins:
    image: tepapa/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/var/jenkins_home:/var/jenkins_home"
      - "/var/jenkins_builds:/var/jenkins_builds"
      - "/var/run/docker.sock:/var/run/docker.sock"